In [4]:
'''Write a function so that the columns of the output matrix are powers of the input vector.  
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, 
the i-th output column is the input vector raised element-wise to the power of N - i - 1.  
 
HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde.'''

'Write a function so that the columns of the output matrix are powers of the input vector.  \nThe order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, \nthe i-th output column is the input vector raised element-wise to the power of N - i - 1.  \n \nHINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde.'

In [6]:
import numpy as np
   
def matrix(ipvector, n, increasing=False):
    
    if not increasing:
        op_matx = np.array([x**(n-1-i) for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    elif increasing:
        op_matx = np.array([x**i for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    
    return op_matx

inputvector = np.array([1,2,3,4,5])
no_col_opmat = 3
dec_order = matrix(inputvector,no_col_opmat,False)
inc_order = matrix(inputvector,no_col_opmat,True)

print("Input:",inputvector,"\n")
print("Number of columns:",no_col_opmat,"\n")
print("Decreasing order of powers:\n\n",dec_order,"\n")
print("Increasing order of powers:\n\n",inc_order,"\n")

Input: [1 2 3 4 5] 

Number of columns: 3 

Decreasing order of powers:

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]] 

Increasing order of powers:

 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]] 

